---
title: "Homework3"
author: "Jeff Nguyen"
date: "15/11/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, envir=.GlobalEnv)
```

**Pre-MFE Probability Seminar**  
**Baruch College, Fall 2020**  


Homework 04  
Student Name: Ngoc Son (Jeff) Nguyen  


# **Question 1**  
  
From the derived generalized formula for n-period option price in class:  

\begin{equation}
  \begin{aligned}
    \Pi_0 =& \frac{1}{(1+r)^n} \sum_{k=0}^{n} \Pi_{n,k} {n \choose k} (p^{*})^k (1-p^{*})^{n-k}  \\
    \text{where} &  \\
    \Pi_{n,k} =& \, \text{payoff when} \, S(n) = S(0)u^k d^{n-k}  \\
  \end{aligned}
\end{equation}
  
We know pay off of European call option at time n is $\Pi_{n,k} = (S(n) - K)^+$.  

In addition: $p^* = \frac{1+r-d}{u-d}$ and $1-p^* = \frac{u-1-r}{u-d}$.  


Thus, rewrite in desirable term:  

\begin{equation}
  \begin{aligned}
    \Pi_0 =& \frac{1}{(1+r)^n} \sum_{k=0}^{n} (S(n) - K)^+ *{n \choose k} \Big(\frac{1+r-d}{u-d}\Big)^k \Big(\frac{u-1-r}{u-d}\Big)^{n-k}  \\
    \text{or} &  \\
    \Pi_0 =& \frac{1}{(1+r)^n} \sum_{k=0}^{n} (S(0)u^k d^{n-k} - K)^+ *{n \choose k} \Big(\frac{1+r-d}{u-d}\Big)^k \Big(\frac{u-1-r}{u-d}\Big)^{n-k}  \\
  \end{aligned}
\end{equation}  
  
# **Question 2**  

Similar to question 1, substitute $\Pi_{n,k} = (K - S(n))^+$  

We have:  

\begin{equation}
  \begin{aligned}
    \Pi_0 =& \frac{1}{(1+r)^n} \sum_{k=0}^{n} (K - S(0)u^k d^{n-k})^+ *{n \choose k} \Big(\frac{1+r-d}{u-d}\Big)^k \Big(\frac{u-1-r}{u-d}\Big)^{n-k}  \\
  \end{aligned}
\end{equation}  

# **Question 3**  

## Pricing digital call option:  

Digital call option pay off is given as follow:  

\begin{equation}
  \begin{aligned}
    \Pi_{n_C} =& \left\{
                 \begin{matrix}
                  1 \quad \text{,iff} \quad S_n \geqslant K \\
                  0 \quad \text{,iff} \quad S_n < K \\
                 \end{matrix}
                 \right. \\
    \text{or}  \\
    f(S_n) =& I_{S_n - K \geqslant 0}  \\
  \end{aligned}
\end{equation}  

We have the initial price $\Pi_{0_c}$ of the call to be: 

\begin{equation}
  \begin{aligned}
    \Pi_{0_C} =& \text{Discount Factor} * E\left(f(S_n) \right)  \\
              =& e^{-rn} * E\left(f(S_n) \right)\\
              =& e^{-rn} * E\left(I_{S_n - K \geqslant 0} \right)  \\
              =& e^{-rn} * P\left(S_n - K \geqslant 0 \right)  \\
              =& e^{-rn} * P\left(S_n \geqslant K \right)  \\
  \end{aligned}
\end{equation} 
  
## Pricing digital put option:   

Digital call option pay off is given as follow:  

\begin{equation}
  \begin{aligned}
    \Pi_{n_P} =& \left\{
                 \begin{matrix}
                  1 \quad \text{,iff} \quad Sn < K \\
                  0 \quad \text{,iff} \quad Sn \geq K \\
                 \end{matrix}
                 \right. \\
    \text{or}  \\
    g(S_n) =& I_{S_n - K < 0}  \\
  \end{aligned}
\end{equation}  

We have the initial price $\Pi_{0_p}$ of the put to be: 

\begin{equation}
  \begin{aligned}
    \Pi_{0_P} =& \text{Discount Factor} * E\left(g(S_n) \right)  \\
              =& e^{-rn} * E\left(g(S_n) \right)\\
              =& e^{-rn} * E\left(I_{S_n - K < 0} \right)  \\
              =& e^{-rn} * P\left(Sn - K < 0 \right)  \\
              =& e^{-rn} * P\left(Sn < K \right)  \\
  \end{aligned}
\end{equation}  

## Pricing the portfolio  

From above, we can see:  

\begin{equation}
  \begin{aligned}
    \Pi_{0_C} + \Pi_{0_P} =& e^{-rn} * P\left(Sn \geqslant K \right) + e^{-rn} * P\left(Sn < K \right)  \\
                          =& e^{-rn} * \left[P\left(Sn \geqslant K \right) + P\left(Sn < K \right) \right]  \\
                          =& e^{-rn} * 1  \\
                          =& e^{-rn}  \\
  \end{aligned}
\end{equation}  

# **Question 4**

## a. Find the distribution of $S_n$  

Every fixed $\omega$ uniquely determines the path $S_0(\omega), S_1(\omega), S_2(\omega), ..., S_n(\omega)$ that can be graphically represented as a path in the coordinated plane.  

A simple symmetric random walk is the one in which all outcomes have the same probability. The cardinality of the set $\Omega$ is $2^n$, i.e. $|\Omega| = 2^n$ hence for each $\omega \in \Omega$, we have $P(\{\omega\}) = \frac{1}{2n}$.  

Looking at the distribution of the end point $S_n(\omega)$, we have $S_n \in \{ a, a\pm 1, a\pm 2, ..., a\pm n \}$. However we can reduce the set of possibilities for $S_n$ if we know whether n is even or odd. If $2 | n$ then there exists a positive integer $m$ such that $n= 2m$. Thus:  

\begin{equation}
  \begin{aligned}
    S_n =& S_{2m} \in \{ a, a \pm 2, a \pm 4, ... , a \pm 2m\}
  \end{aligned}
\end{equation}  
  
If $2|n$ then there exists a non-negative integer $m$ such that $n= 2m + 1$. In this case, we can conclude:  

\begin{equation}
  \begin{aligned}
    S_n =& S_{2m+1} \in \{ a \pm 1, a \pm 3, a \pm 5, ... , a \pm (2m+1) \}
  \end{aligned}
\end{equation}  

To find the distribution $P(S_n = b)$, we need to count the number of outcomes $\omega \in \Omega$ for which $S_n(\omega) = b$.  

We have:  

\begin{equation}
  \begin{aligned}
    \left\{
      \begin{matrix}
        \#1 + \#(-1) =& n  \\
        \#1 - \#(-1) =& b-a \\
      \end{matrix}
    \right.  \\
    \text{The solution of the linear system above is:}  \\
    \left\{
      \begin{matrix}
        \#1 =& \frac{n-a+b}{2}  \\
        \#(-1) =& \frac{n+a-b}{2} \\
      \end{matrix}
    \right.  \\
  \end{aligned}
\end{equation}  

Thus, for the sum of $n \pm 1$ to be equal to $b-a$, it is necessary and sufficent to have $\frac{n-a+b}{2}$ 1s, and $\frac{n+a-b}{2}$ (-1)s. There are ${n \choose \frac{n-a+b}{2}}$ outcomes with this property. Therefore:  

\begin{equation}
  \begin{aligned}
    P(S_n = b) =& {n \choose \frac{n-a+b}{2}} * 2^{-n} \\
  \end{aligned}
\end{equation}  

## b. Distribution of paths

Recall the following identity proved in the lecture:  

\begin{equation}
  \begin{aligned}
    P(S_n = b) =& {n \choose \frac{1}{2}*(n+b-a)} * 2^{-n} \\
  \end{aligned}
\end{equation} 

Thus:

\begin{equation}
  \begin{aligned}
    P(\omega|S_n = b) =& \frac{2^{-n}}{{n \choose \frac{1}{2}*(n+b-a)} * 2^{-n}} \\
                      =& \frac{1}{{n \choose \frac{1}{2}*(n+b-a)}}  \\
  \end{aligned}
\end{equation} 

We can see that the answer is independent on $p$. The distribution of paths end up at b follows a binomial distribution.  


# **Question 5**   

## Reflection principle  

We have:  

\begin{equation}
  \begin{aligned}
    \left\{
      \begin{matrix}
        \#1 + \#(-1) =& n  \\
        \#1 - \#(-1) =& b-2a \\
      \end{matrix}
    \right.  \\
    \text{The solution of the linear system above is:}  \\
    \left\{
      \begin{matrix}
        \#1 =& \frac{n+b}{2} - a  \\
        \#(-1) =& \frac{n-b}{2} + a \\
      \end{matrix}
    \right.  \\
  \end{aligned}
\end{equation}  

Thus:  $P(S_n = 2a - b) = 2^{-n} * {n \choose \frac{n+b}{2}+a}$.  
  
\begin{equation}
  \begin{aligned}
    P(S_n = 2a - b) =& 2^{-n} * \frac{n!}{\left( \frac{n+b}{2} + a \right)! * \left( n-\frac{n+b}{2} - a \right)!}  \\
                    =& 2^{-n} * \frac{n!}{\left( \frac{n+b}{2} + a \right)! * \left( \frac{n+b}{2} - a \right)!} \\
  \end{aligned}
\end{equation} 
  
Based on the reflection principle with $S_n$ being a symmetric random walk, we have:  

\begin{equation}
  \begin{aligned}
    P_{2a} \left( S_n^* \geqslant a,  S_n = b\right) = 2^{-n} * N(-2a,b) =& P_{-2a}(S_n = 2a - b)  \\
    \text{Based on the property above:}  \\
    P(S_n^* \geqslant a, S_n = b) = P(S_n = 2a - b) =& 2^{-n} * \frac{n!}{\left( \frac{n+b}{2} + a \right)! * \left( \frac{n+b}{2} - a \right)!}\\
  \end{aligned}
\end{equation} 

## Find $P(S_n^* < a, S_n = b)$  

Recall: $P(S_n = b) = {n \choose \frac{n-a+b}{2}} * 2^{-n}$
  
Thus, from the above:  

\begin{equation}
  \begin{aligned}
    P(S*n < a, S_n = b) =& P(S_n = b) - P(S_n^* \geqslant a, S_n =b)  \\
                        =& {n \choose \frac{n-a+b}{2}} * 2^{-n} - 
                           {n \choose \frac{n+b}{2}+a} * 2^{-n} \\
                        =& 2^{-n} * 
                           \left[ 
                            {n \choose \frac{n-a+b}{2}} - {n \choose \frac{n+b}{2}+a}
                           \right]  \\
  \end{aligned}
\end{equation} 
  
# **Question 6**   

The stock price tree and payoffs of the option are given in the following tree:  
  
  
|n=0          | n=1          | n=2               | n=3                   | n=4                     | Payoffs
|---          | ---          | ---               | ---                   | ---                     | ---  
|             |              |                   |                       | $S_{u^4} = 146.484375$  | 0
|             |              |                   | $S_{u^3} = 117.1875$  |                         | 
|             |              | $S_{u^2} = 93.75$ |                       | $S_{u^3d} = 93.75$      | 0
|             | $S_{u} = 75$ |                   | $S_{u^2d} = 75$       |                         | 
|$S_{0} = 60$ |              | $S_{ud} = 60$     |                       | $S_{u^2d^2} = 60$       | 0
|             | $S_{d} = 48$ |                   | $S_{ud^2} = 48$       |                         | 
|             |              | $S_{d^2} = 38.4$  |                       | $S_{ud^3} = 38.4$       | $59 - 38.04 = 20.6$
|             |              |                   | $S_{d^3} = 30.72$     |                         | 
|             |              |                   |                       | $S_{d^4} = 24.576$      | $59 - 24.576 = 34.424$
  

Then we obtain $p^* = \frac{1+r-d}{u-d} = .555555556$.  

## First method: "Path counting"  

The price is given by:  

\begin{equation}
  \begin{aligned}
    \Pi_0 =& \frac{1}{(1+r)^4} * E_{*}(Payoff)  \\
          =& \frac{1}{(1+r)^4} * \left[ 
                                  \begin{matrix}
                                        20.6 * P_{*}(\text{Stock achieve price 38.4 after dipping below 35}) + \qquad\qquad\qquad\\
                                        34.424 * P_{*}(\text{Stock achieve price 24.576 after dipping below 35}) \\
                                  \end{matrix}
                                 \right]  \\
          =& \frac{1}{(1+r)^4} * \left[ 
                                  \begin{matrix}
                                        20.6 * P_{*}(\text{Stock goes up once, goes down 3 times, and dip below 35 at least once}) +         \qquad\qquad\qquad\quad\\
                                        34.424 * P_{*}(\text{Stock does not goes up, goes down 4 times, and dip below 35 at least once}) \\
                                  \end{matrix}
                                 \right]  \\
          =& \frac{1}{(1+r)^4} * \left[ 
                                    \begin{matrix}
                                        20.6 * p_{*}^1 * (1 - p_{*})^3 * P_{*}(\text{Number of good paths from (0,-1) to (4,1)}) + \qquad\qquad\qquad\quad\\
                                        34.424 * p_{*}^0 * (1 - p_{*})^4 * P_{*}(\text{Number of good paths from (0,-1) to (4,3)}) \\
                                    \end{matrix}
                                  \right]  \\
          =& \frac{1}{(1+r)^4} * \left[ 
                                    \begin{matrix}
                                        20.6 * p_{*}^1 * (1 - p_{*})^3 * G_4(1,1) + \qquad\qquad\qquad\quad\\
                                        34.424 * p_{*}^0 * (1 - p_{*})^4 * G_4(1,3)) \\
                                    \end{matrix}
                                  \right]  \\
          =& \frac{1}{(1+r)^4} * \left[ 
                                    \begin{matrix}
                                        20.6 * p_{*}^1 * (1 - p_{*})^3 * [N_4(1,1) - N_4(-1,1)] + \qquad\qquad\qquad\quad\\
                                        34.424 * p_{*}^0 * (1 - p_{*})^4 * [N_4(1,3) - N_4(-1,3)] \\
                                    \end{matrix}
                                  \right]  \\
          =& 1.931619\\
  \end{aligned}
\end{equation} 

Thus, the price of the option is $\Pi_{0} = 1.931619$.  

## Second method: Backward recursive  

Calculations:  

\begin{equation}
  \begin{aligned}
    \text{At time} \, n=4:  \\
    \Pi_{u^4} =& (59 - 146.484375)^+ = 0 \\
    \Pi_{u^3d} =& (59 - 93.75)^+ = 0 \\
    \Pi_{u^2d^2} =& (59 - 60)^+ = 0 \\
    \Pi_{ud^3} =& (59 - 38.4)^+ = 20.6 \\
    \Pi_{d^4} =& (59 - 24.576)^+ = 34.424 \\
    \text{At time} \, n=3:  \\
    \Pi_{u^3} =& \frac{1}{1+r} * (\Pi_{u^4}*p^{*} + \Pi_{u^3d}*(1-p^{*})) = 0 \\
    \Pi_{u^2d} =& \frac{1}{1+r} * (\Pi_{u^3d}*p^{*} + \Pi_{u^2d^2}*(1-p^{*})) = 0 \\
    \Pi_{ud^2} =& 0 \, \text{because at this node, the option would have not hit the barrier and therefore, worthless} \\
    \Pi_{d^3} =& \frac{1}{1+r} * (\Pi_{ud^3}*p^{*} + \Pi_{d^4}*(1-p^{*})) = 25.47047619 \\
    \text{At time} \, n=2:  \\
    \Pi_{u^2} =& \frac{1}{1+r} * (\Pi_{u^3}*p^{*} + \Pi_{u^2d}*(1-p^{*})) = 0 \\
    \Pi_{ud} =& \frac{1}{1+r} * (\Pi_{u^2d}*p^{*} + \Pi_{ud^2}*(1-p^{*})) = 0 \\
    \Pi_{d^2} =& \frac{1}{1+r} * (\Pi_{ud^2}*p^{*} + \Pi_{d^3}*(1-p^{*})) = 10.78115 \\
    \text{At time} \, n=1:  \\
    \Pi_{u} =& \frac{1}{1+r} * (\Pi_{u^2}*p^{*} + \Pi_{ud}*(1-p^{*})) = 0 \\
    \Pi_{d} =& \frac{1}{1+r} * (\Pi_{ud}*p^{*} + \Pi_{d^2}*(1-p^{*})) = 4.56345 \\
    \text{At time} \, n=0:  \\
    \Pi_{0} =& \frac{1}{1+r} * (\Pi_{u}*p^{*} + \Pi_{d}*(1-p^{*})) = 1.931619 \\
  \end{aligned}
\end{equation} 

The option price tree is given by the tree below:     

  
| n=0                     | n=1                     | n=2                      | n=3                       | n=4             
| ---                     | ---                     | ---                      | ---                       | ---             
|                         |                         |                          |                           | $\Pi_{u^4} = 0$ 
|                         |                         |                          | $\Pi_{u^3} = 0$           |                  
|                         |                         | $\Pi_{u^2} = 0$          |                           | $\Pi_{u^3d} = 0$
|                         | $\Pi_{u} = 0$           |                          | $\Pi_{u^2d} = 0$          |                     
| $\Pi_{0} = 1.931619$    |                         | $\Pi_{ud} = 0$           |                           | $\Pi_{u^2d^2} = 0$  
|                         | $\Pi_{d} = 4.56345$     |                          | $\Pi_{ud^2} = 0$          |                     
|                         |                         | $\Pi_{d^2} = 10.78115$   |                           | $\Pi_{ud^3} = 20.6$
|                         |                         |                          | $\Pi_{d^3} = 25.47047619$ |                      
|                         |                         |                          |                           | $\Pi_{d^4} = 34.424$  
  
Thus, the price of the option is $\Pi_{0} = 1.931619$.  

# **Question 7**   

Recall: The stock price tree and payoffs of the option are given in the following tree:  
  
  
|n=0          | n=1          | n=2               | n=3                   | n=4                     | Payoffs
|---          | ---          | ---               | ---                   | ---                     | ---  
|             |              |                   |                       | $S_{u^4} = 146.484375$  | 0
|             |              |                   | $S_{u^3} = 117.1875$  |                         | 
|             |              | $S_{u^2} = 93.75$ |                       | $S_{u^3d} = 93.75$      | 0
|             | $S_{u} = 75$ |                   | $S_{u^2d} = 75$       |                         | 
|$S_{0} = 60$ |              | $S_{ud} = 60$     |                       | $S_{u^2d^2} = 60$       | 0
|             | $S_{d} = 48$ |                   | $S_{ud^2} = 48$       |                         | 
|             |              | $S_{d^2} = 38.4$  |                       | $S_{ud^3} = 38.4$       | $59 - 38.04 = 20.6$
|             |              |                   | $S_{d^3} = 30.72$     |                         | 
|             |              |                   |                       | $S_{d^4} = 24.576$      | $59 - 24.576 = 34.424$
  

Then we obtain $p^* = \frac{1+r-d}{u-d} = .555555556$.  

Using backward induction and take into account early exercise:  

The American option price tree is given by:  

  
| n=0       | n=1       | n=2             | n=3                       | n=4             
| ---       | ---       | ---             | ---                       | ---             
|           |           |                 |                           | $\Pi_{u^4} = 0$ 
|           |           |                 | $\Pi_{u^3} = 0$           |                  
|           |           | $\Pi_{u^2} = 0$ |                           | $\Pi_{u^3d} = 0$
|           | $\Pi_{u}$ |                 | $\Pi_{u^2d} = 0$          |                     
| $\Pi_{0}$ |           | $\Pi_{ud}$      |                           | $\Pi_{u^2d^2} = 0$  
|           | $\Pi_{d}$ |                 | $\Pi_{ud^2}$              |                     
|           |           | $\Pi_{d^2}$     |                           | $\Pi_{ud^3} = 20.6$
|           |           |                 | $\Pi_{d^3}$               |                      
|           |           |                 |                           | $\Pi_{d^4} = 34.424$  
  
\begin{equation}
  \begin{aligned}
    \text{At time} \, n=4:  \\
    \Pi_{u^4, US} =& (59 - 146.484375)^+ = 0 \\
    \Pi_{u^3d, US} =& (59 - 93.75)^+ = 0 \\
    \Pi_{u^2d^2, US} =& (59 - 60)^+ = 0 \\
    \Pi_{ud^3, US} =& (59 - 38.4)^+ = 20.6 \\
    \Pi_{d^4, US} =& (59 - 24.576)^+ = 34.424 \\
    \text{At time} \, n=3:  \\
    \Pi_{u^3, US} =& \frac{1}{1+r} * (\Pi_{u^4}*p^{*} + \Pi_{u^3d}*(1-p^{*})) = 0 \\
    \Pi_{u^2d, US} =& \frac{1}{1+r} * (\Pi_{u^3d}*p^{*} + \Pi_{u^2d^2}*(1-p^{*})) = 0 \\
    \Pi_{ud^2, EU} =& \frac{1}{1+r} * (\Pi_{u^2d^2}*p^{*} + \Pi_{ud^3}*(1-p^{*})) = 8.71957672 \\
    \text{Early exercise payoff} \, V_{ud^2} =& (59 - 48)^+ = 11 \\
    \text{Thus, under no-arbitrage:} \, \Pi_{ud^2, US} =& 11  \\
    \Pi_{d^3, EU} =& \frac{1}{1+r} * (\Pi_{ud^3}*p^{*} + \Pi_{d^4}*(1-p^{*})) = 25.47047619 \\
    \text{Early exercise payoff} \, V_{d^3} =& (59 - 30.72)^+ = 28.28 \\
    \text{Thus, under no-arbitrage:} \, \Pi_{d^3, US} =& 28.28  \\
    \text{At time} \, n=2:  \\
    \Pi_{u^2} =& \frac{1}{1+r} * (\Pi_{u^3}*p^{*} + \Pi_{u^2d}*(1-p^{*})) = 0 \\
    \Pi_{ud, EU} =& \frac{1}{1+r} * (\Pi_{u^2d}*p^{*} + \Pi_{ud^2}*(1-p^{*})) = 4.656085 \\
    \text{Early exercise payoff} \, V_{ud} =& (59 - 90)^+ = 0 \\
    \text{Thus, under no-arbitrage:} \, \Pi_{ud, US} =& 4.656085  \\
    \Pi_{d^2, EU} =& \frac{1}{1+r} * (\Pi_{ud^2}*p^{*} + \Pi_{d^3}*(1-p^{*})) = 17.79048 \\
    \text{Early exercise payoff} \, V_{d^2} =& (59 - 38.4)^+ = 20.6 \\
    \text{Thus, under no-arbitrage:} \, \Pi_{d^2, US} =& 20.6  \\
    \text{At time} \, `n=1:  \\
    \Pi_{u, EU} =& \frac{1}{1+r} * (\Pi_{u^2}*p^{*} + \Pi_{ud}*(1-p^{*})) = 1.97083 \\
    \text{Early exercise payoff} \, V_{u} =& (59 - 75)^+ = 0 \\
    \text{Thus, under no-arbitrage:} \, \Pi_{u, US} =& 1.97083  \\
    \Pi_{d, EU} =& \frac{1}{1+r} * (\Pi_{ud}*p^{*} + \Pi_{d^2}*(1-p^{*})) = 11.18311 \\
    \text{Early exercise payoff} \, V_{d} =& (59 - 48)^+ = 11 \\
    \text{Thus, under no-arbitrage:} \, \Pi_{u, US} =& 11.18311  \\
    \text{At time} \, n=0:  \\
    \Pi_{0} =& \frac{1}{1+r} * (\Pi_{u}*p^{*} + \Pi_{d}*(1-p^{*})) = 5.776359 \\
  \end{aligned}
\end{equation}  

The American option price tree is given by:  

  
| n=0                  | n=1                  | n=2                   | n=3                 | n=4             
| ---                  | ---                  | ---                   | ---                 | ---             
|                      |                      |                       |                     | $\Pi_{u^4} = 0$ 
|                      |                      |                       | $\Pi_{u^3} = 0$     |                  
|                      |                      | $\Pi_{u^2} = 0$       |                     | $\Pi_{u^3d} = 0$
|                      | $\Pi_{u} = 1.97083$  |                       | $\Pi_{u^2d} = 0$    |                     
| $\Pi_{0} = 5.776359$ |                      | $\Pi_{ud} = 4.656085$ |                     | $\Pi_{u^2d^2} = 0$  
|                      | $\Pi_{d} = 11.18311$ |                       | $\Pi_{ud^2} = 11$   |                     
|                      |                      | $\Pi_{d^2} = 20.6$    |                     | $\Pi_{ud^3} = 20.6$
|                      |                      |                       | $\Pi_{d^3} = 28.28$ |                      
|                      |                      |                       |                     | $\Pi_{d^4} = 34.424$  
  
Thus, the price of the option is $\Pi_{0} = 5.776359$.  

# **Question 8**   

## Using Exercise 2 formula:  

From exercise 2, we have:  

\begin{equation}
  \begin{aligned}
    \Pi_0 =& \frac{1}{(1+r)^n} \sum_{k=0}^{n} (K - S(0)u^k d^{n-k})^+ {n \choose k} \Big(\frac{1+r-d}{u-d}\Big)^k \Big(\frac{u-1-r}{u-d}\Big)^{n-k}  \\
  \end{aligned}
\end{equation}  

Plug in: $r=.05, n=4, K=59, S(0)=60, u=1.25, d=.8$.  

In addtion: $\frac{1+r-d}{u-d} = \frac{1+.5-.8}{1.25-.8} = \frac{5}{9}$, and $\frac{u-1-r}{u-d} = 1 - \frac{5}{9} = \frac{4}{9}$.  

Thus:  
\begin{equation}
  \begin{aligned}
    \Pi_0 =& \frac{1}{(1+r)^n} \sum_{k=0}^{n} (K - S(0)u^k d^{n-k})^+ *{n \choose k} \Big(\frac{1+r-d}{u-d}\Big)^k \Big(\frac{u-1-r}{u-d}\Big)^{n-k}  \\
          =& \frac{1}{(1+.05)^4} \sum_{k=0}^{4} (59 - 60*1.25^k*.8^{n-k})^+ *{4 \choose k} \Big(\frac{5}{9}\Big)^k \Big(\frac{4}{9}\Big)^{4-k}  \\
          =& \frac{1}{1.05^4} * \left[ 
                                \begin{matrix}
                                  (59 - 60*1.25^0*.8^4)^+ *{4 \choose 0} \Big(\frac{5}{9}\Big)^0 \Big(\frac{4}{9}\Big)^4  + \\
                                  (59 - 60*1.25^1*.8^3)^+ *{4 \choose 1} \Big(\frac{5}{9}\Big)^1 \Big(\frac{4}{9}\Big)^3  + \\
                                  (59 - 60*1.25^2*.8^2)^+ *{4 \choose 2} \Big(\frac{5}{9}\Big)^2 \Big(\frac{4}{9}\Big)^2  + \\
                                  (59 - 60*1.25^3*.8^1)^+ *{4 \choose 3} \Big(\frac{5}{9}\Big)^3 \Big(\frac{4}{9}\Big)^1  + \\
                                  (59 - 60*1.25^4*.8^0)^+ *{4 \choose 4} \Big(\frac{5}{9}\Big)^4 \Big(\frac{4}{9}\Big)^0 \\
                                \end{matrix}
                                \right]  \\
          =& \frac{1}{1.05^4} * \left[ 
                                  \begin{matrix}
                                    34.24 *{4 \choose 0} \Big(\frac{5}{9}\Big)^0 \Big(\frac{4}{9}\Big)^4  + \\
                                    20.6 *{4 \choose 1} \Big(\frac{5}{9}\Big)^1 \Big(\frac{4}{9}\Big)^3  + \\
                                    0 *{4 \choose 2} \Big(\frac{5}{9}\Big)^2 \Big(\frac{4}{9}\Big)^2  + \\
                                    0 *{4 \choose 3} \Big(\frac{5}{9}\Big)^3 \Big(\frac{4}{9}\Big)^1  + \\
                                    0 *{4 \choose 4} \Big(\frac{5}{9}\Big)^4 \Big(\frac{4}{9}\Big)^0 \\
                                  \end{matrix}
                                  \right]  \\
          =& \frac{1}{1.05^4} * \left[ 
                                  \begin{matrix}
                                    34.24 * 1 * 1 * \Big(\frac{256}{6561}\Big)  + \\
                                    20.6 * 4 * \Big(\frac{5}{9}\Big) * \Big(\frac{64}{729}\Big)  \\
                                  \end{matrix}
                                  \right]  \\
          =& 4.411388601  \\
  \end{aligned}
\end{equation}  

## Using Method 2: Backward Recursion    

Calculations:  

\begin{equation}
  \begin{aligned}
    \text{At time} \, n=4:  \\
    \Pi_{u^4} =& (59 - 146.484375)^+ = 0 \\
    \Pi_{u^3d} =& (59 - 93.75)^+ = 0 \\
    \Pi_{u^2d^2} =& (59 - 60)^+ = 0 \\
    \Pi_{ud^3} =& (59 - 38.4)^+ = 20.6 \\
    \Pi_{d^4} =& (59 - 24.576)^+ = 34.424 \\
    \text{At time} \, n=3:  \\
    \Pi_{u^3} =& \frac{1}{1+r} * (\Pi_{u^4}*p^{*} + \Pi_{u^3d}*(1-p^{*})) = 0 \\
    \Pi_{u^2d} =& \frac{1}{1+r} * (\Pi_{u^3d}*p^{*} + \Pi_{u^2d^2}*(1-p^{*})) = 0 \\
    \Pi_{ud^2} =& \frac{1}{1+r} * (\Pi_{u^2d^2}*p^{*} + \Pi_{ud^3}*(1-p^{*})) = 8.71957672 \\
    \Pi_{d^3} =& \frac{1}{1+r} * (\Pi_{ud^3}*p^{*} + \Pi_{d^4}*(1-p^{*})) = 25.47047619 \\
    \text{At time} \, n=2:  \\
    \Pi_{u^2} =& \frac{1}{1+r} * (\Pi_{u^3}*p^{*} + \Pi_{u^2d}*(1-p^{*})) = 0 \\
    \Pi_{ud} =& \frac{1}{1+r} * (\Pi_{u^2d}*p^{*} + \Pi_{ud^2}*(1-p^{*})) = 3.690826125 \\
    \Pi_{d^2} =& \frac{1}{1+r} * (\Pi_{ud^2}*p^{*} + \Pi_{d^3}*(1-p^{*})) = 15.3946866 \\
    \text{At time} \, n=1:  \\
    \Pi_{u} =& \frac{1}{1+r} * (\Pi_{u^2}*p^{*} + \Pi_{ud}*(1-p^{*})) = 1.562254444 \\
    \Pi_{d} =& \frac{1}{1+r} * (\Pi_{ud}*p^{*} + \Pi_{d^2}*(1-p^{*})) = 8.469087516 \\
    \text{At time} \, n=0:  \\
    \Pi_{0} =& \frac{1}{1+r} * (\Pi_{u}*p^{*} + \Pi_{d}*(1-p^{*})) = 4.411388601 \\
  \end{aligned}
\end{equation} 

The option price tree is given by the tree below:     

  
| n=0                     | n=1                     | n=2                      | n=3                       | n=4             
| ---                     | ---                     | ---                      | ---                       | ---             
|                         |                         |                          |                           | $\Pi_{u^4} = 0$ 
|                         |                         |                          | $\Pi_{u^3} = 0$           |                  
|                         |                         | $\Pi_{u^2} = 0$          |                           | $\Pi_{u^3d} = 0$
|                         | $\Pi_{u} = 1.562254444$ |                          | $\Pi_{u^2d} = 0$          |                     
| $\Pi_{0} = 4.411388601$ |                         | $\Pi_{ud} = 3.690826125$ |                           | $\Pi_{u^2d^2} = 0$  
|                         | $\Pi_{d} = 8.469087516$ |                          | $\Pi_{ud^2} = 8.71957672$ |                     
|                         |                         | $\Pi_{d^2} = 15.3946866$ |                           | $\Pi_{ud^3} = 20.6$
|                         |                         |                          | $\Pi_{d^3} = 25.47047619$ |                      
|                         |                         |                          |                           | $\Pi_{d^4} = 34.424$  
  
Thus, the price of the option is $\Pi_{0} = 4.411388601$.  
  
# **Question 9**  
No clue.  

# **Question 10**   

## Price an up-and-out call option.

Based on the lecture, the price is given by:  

\begin{equation}
  \begin{aligned}
    \Pi_0 =& \frac{1}{(1+r)^n} * E_{*} \left[ (S_n - K)^{+} * 1_{S_n^{*} < B} \right]  \\
          =& \frac{1}{(1+r)^n} * \sum\limits_{b: K < b < B} (b-K) * P_{*} \left( S_n^* < B, S_n = b \right)  \\
          =& \frac{1}{(1+r)^n} * \sum\limits_{b: K < b < B} (b-K) * P_{*} \left( W_n^* < \frac{lnB - lnS}{lnu}, W_n = \frac{lnb - lnS}{lnu} \right) \\
  \end{aligned}
\end{equation} 

With the specific case $u=1.25, d=.8, S=60, r=.05, n=4, K=90, B=115$:  

  
|n=0          | n=1          | n=2               | n=3                   | n=4                     | Payoffs
|---          | ---          | ---               | ---                   | ---                     | ---  
|             |              |                   |                       | $S_{u^4} = 146.484375$  | 0
|             |              |                   | $S_{u^3} = 117.1875$  |                         | 
|             |              | $S_{u^2} = 93.75$ |                       | $S_{u^3d} = 93.75$      | $93.75 - 90 = 3.75$
|             | $S_{u} = 75$ |                   | $S_{u^2d} = 75$       |                         | 
|$S_{0} = 60$ |              | $S_{ud} = 60$     |                       | $S_{u^2d^2} = 60$       | 0
|             | $S_{d} = 48$ |                   | $S_{ud^2} = 48$       |                         | 
|             |              | $S_{d^2} = 38.4$  |                       | $S_{ud^3} = 38.4$       | 0
|             |              |                   | $S_{d^3} = 30.72$     |                         | 
|             |              |                   |                       | $S_{d^4} = 24.576$      | 0

The corresponded option table is:    

  
| n=0                    | n=1                   | n=2                      | n=3                       | n=4             
| ---                    | ---                   | ---                      | ---                       | ---             
|                        |                       |                          |                           | $\Pi_{u^4} = 0$ 
|                        |                       |                          | $\Pi_{u^3} = 0$           |                  
|                        |                       | $\Pi_{u^2} = .83984211$  |                           | $\Pi_{u^3d} = 3.75$
|                        | $\Pi_{u} = .888721809$|                          | $\Pi_{u^2d} = 1.984126984$|                     
| $\Pi_{0} = .705334769$ |                       | $\Pi_{ud} = 1.049802637$ |                           | $\Pi_{u^2d^2} = 0$  
|                        | $\Pi_{d} = .55545113$ |                          | $\Pi_{ud^2} = 0$          |                     
|                        |                       | $\Pi_{d^2} = 0$          |                           | $\Pi_{ud^3} = 0$
|                        |                       |                          | $\Pi_{d^3} = 0$           |                      
|                        |                       |                          |                           | $\Pi_{d^4} = 0$  
  
Thus, the price of the option is $\Pi_{0} = .705334769$.  

## Price an up-and-out call with K=59, B=90  

We have the pay-offs table as follow. Note that the option in knocked-out if the underlying goes above $B=90$ and also expire worthless if the underlying price at time $n=4$ is below $K=59$  
  
|n=0          | n=1          | n=2               | n=3                   | n=4                     | Payoffs
|---          | ---          | ---               | ---                   | ---                     | ---  
|             |              |                   |                       | $S_{u^4} = 146.484375$  | 0
|             |              |                   | $S_{u^3} = 117.1875$  |                         | 
|             |              | $S_{u^2} = 93.75$ |                       | $S_{u^3d} = 93.75$      | 0
|             | $S_{u} = 75$ |                   | $S_{u^2d} = 75$       |                         | 
|$S_{0} = 60$ |              | $S_{ud} = 60$     |                       | $S_{u^2d^2} = 60$       | $60 -59 = 1$
|             | $S_{d} = 48$ |                   | $S_{ud^2} = 48$       |                         | 
|             |              | $S_{d^2} = 38.4$  |                       | $S_{ud^3} = 38.4$       | 0
|             |              |                   | $S_{d^3} = 30.72$     |                         | 
|             |              |                   |                       | $S_{d^4} = 24.576$      | 0
  
Recall $p^* = \frac{1+r-d}{u-d} = \frac{5}{9}$.  

Using backwards recursion:  

\begin{equation}
  \begin{aligned}
    \text{At time} \, n=4:  \\
    \Pi_{u^4} =& 0 \, \text{knocked out}  \\
    \Pi_{u^3d} =& 0 \, \text{knocked out}  \\
    \Pi_{u^2d^2} =& (60 - 59)^+ = 1 \\
    \Pi_{ud^3} =& (38.4 - 59)^+ = 0 \\
    \Pi_{d^4} =& (24.576 - 59)^+ = 0 \\
    \text{At time} \, n=3:  \\
    \Pi_{u^3} =& \frac{1}{1+r} * (\Pi_{u^4}*p^{*} + \Pi_{u^3d}*(1-p^{*})) = 0 \\
    \Pi_{u^2d} =& \frac{1}{1+r} * (\Pi_{u^3d}*p^{*} + \Pi_{u^2d^2}*(1-p^{*})) = .4232804 \\
    \Pi_{ud^2} =& \frac{1}{1+r} * (\Pi_{u^2d^2}*p^{*} + \Pi_{ud^3}*(1-p^{*})) = .5291005 \\
    \Pi_{d^3} =& \frac{1}{1+r} * (\Pi_{ud^3}*p^{*} + \Pi_{d^4}*(1-p^{*})) = 0 \\
    \text{At time} \, n=2:  \\
    \Pi_{u^2} =& \frac{1}{1+r} * (\Pi_{u^3}*p^{*} + \Pi_{u^2d}*(1-p^{*})) = 0 \\
    \Pi_{ud} =& \frac{1}{1+r} * (\Pi_{u^2d}*p^{*} + \Pi_{ud^2}*(1-p^{*})) = .4479158 \\
    \Pi_{d^2} =& \frac{1}{1+r} * (\Pi_{ud^2}*p^{*} + \Pi_{d^3}*(1-p^{*})) = .2799474 \\
    \text{At time} \, n=1:  \\
    \Pi_{u} =& \frac{1}{1+r} * (\Pi_{u^2}*p^{*} + \Pi_{ud}*(1-p^{*})) = .189594 \\
    \Pi_{d} =& \frac{1}{1+r} * (\Pi_{ud}*p^{*} + \Pi_{d^2}*(1-p^{*})) = .3554887 \\
    \text{At time} \, n=0:  \\
    \Pi_{0} =& \frac{1}{1+r} * (\Pi_{u}*p^{*} + \Pi_{d}*(1-p^{*})) = .2507857 \\
  \end{aligned}
\end{equation} 

The option price tree is given by the tree below:     

  
| n=0                  | n=1                  | n=2                    | n=3                     | n=4             
| ---                  | ---                  | ---                    | ---                     | ---             
|                      |                      |                        |                         | $\Pi_{u^4} = 0$ 
|                      |                      |                        | $\Pi_{u^3} = 0$         |                  
|                      |                      | $\Pi_{u^2} = 0$        |                         | $\Pi_{u^3d} = 0$
|                      | $\Pi_{u} = .189594$  |                        | $\Pi_{u^2d} = .4232804$ |                     
| $\Pi_{0} = .2507857$ |                      | $\Pi_{ud} = .4479158$  |                         | $\Pi_{u^2d^2} = 1$  
|                      | $\Pi_{d} = .3554887$ |                        | $\Pi_{ud^2} = .5291005$ |                     
|                      |                      | $\Pi_{d^2} = .2799474$ |                         | $\Pi_{ud^3} = 0$
|                      |                      |                        | $\Pi_{d^3} = 0$         |                      
|                      |                      |                        |                         | $\Pi_{d^4} = 0$  
  
Thus, the price of the option is $\Pi_{0} = .2507857$.  


