---
title: "Homework3"
author: "Jeff Nguyen"
date: "15/11/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, envir=.GlobalEnv)
```
  
**Pre-MFE Probability Seminar**  
**Baruch College, Fall 2020**  


Homework 03  
Student Name: Ngoc Son (Jeff) Nguyen  


# **Question 1**  
 
## (a) Show that this is indeed a probability mass function.

The probability mass function, $p_{X,Y}(i,j)$ of the random vector (X,Y) has the following properties:

**1. All probabilities are positive:**  
We see this to be true based on the table below with $p_{X,Y}(i,j) = \frac{1}{10} > 0$.  
**2. Any event in the distribution has a probability of happening of between 0 and 1 (e.g. 0% and 100%).**  
We see this to also be true with based on the table below.  
**3. The sum of all probabilities is 100% (i.e. 1 as a decimal):**  
Or $\sum\limits_{i,j = 1, i \leqslant j}^4 p_{X,Y}(i,j) = 1$. We see this to also be true based on the table below.  

(i,j) = (row,col)          | 1               | 2                | 3               | 4              | X (Marginal)
---          | ---             | ---              | ---             | ---            | ---  
1            | $\frac{1}{10}$  | $\frac{1}{10}$   | $\frac{1}{10}$  | $\frac{1}{10}$ | $\frac{2}{5}$
2            | $0$             | $\frac{1}{10}$   | $\frac{1}{10}$  | $\frac{1}{10}$ | $\frac{3}{10}$
3            | $0$             | $0$              | $\frac{1}{10}$  | $\frac{1}{10}$ | $\frac{1}{5}$
4            | $0$             | $0$              | $0$             | $\frac{1}{10}$ | $\frac{1}{10}$
Y (marginal) | $\frac{1}{10}$  | $\frac{1}{5}$    | $\frac{3}{10}$  | $\frac{2}{5}$  | $1$
  
## (b) Compute the marginal distributions of X and Y.  
Computed in the table above.  

## (c) Are X and Y independent?  
Recall that random variables X and Y are independent if $P(X=i, Y=j) = P(X=i) * P(Y=j) \quad \forall i,j$.  

From the table above:  
\begin{equation}
  \begin{aligned}
    P(X=1, Y=1) & = \frac{1}{10}  \\
    P(X=1)*P(Y=1) & = \frac{2}{5} * \frac{1}{10} = \frac{1}{25}  \\
  \end{aligned}
\end{equation}
  
We can see that: $P(X=1, Y=1) \neq P(X=1)*P(Y=1)$.  
Thus, X and Y are not independent.  

## (d) Compute E(XY ).  

\begin{equation}
  \begin{aligned}
    E(X,Y) =& \sum\limits_{i,j} i*j*P(X=i, Y=j) \\
           =& 1*1*P(X=1, Y=1) + 1*2*P(X=1, Y=2) + 1*3*P(X=1, Y=3) + 1*4*P(X=1, Y=4) +  \\
            & 2*2*P(X=2, Y=2) + 2*3*P(X=2, Y=3) + 2*4*P(X=2, Y=4) +  \\
            & 3*3*P(X=3, Y=3) + 3*4*P(X=3, Y=4) +  \\
            & 4*4*P(X=4, Y=4)  \\
           =& \frac{1}{10} + 2*\frac{1}{10} + 3*\frac{1}{10} + 4*\frac{1}{10} +   \\
            & 4*\frac{1}{10} + 6*\frac{1}{10} + 8*\frac{1}{10} +  \\
            & 9*\frac{1}{10} + 12*\frac{1}{10} +  \\
            & 16*\frac{1}{10}  \\
           =& \frac{1}{10} + \frac{1}{5} + \frac{3}{10} + \frac{2}{5} +   \\
            & \frac{2}{5} + \frac{3}{5} + \frac{4}{5} +  \\
            & \frac{9}{10} + \frac{6}{5} +  \\
            & \frac{8}{5}  \\
           =& \frac{13}{2} \\
  \end{aligned}
\end{equation}
  
# **Question 2**  

We have: $E(X|Y=y) = \sum\limits_{x} x*p_{X|Y}(x|y)$. Thus:  

\begin{equation}
  \begin{aligned}
    E(X|Y=1) =& 1*p_{X|Y}(1|1) + 2*p_{X|Y}(2|1) + 3*p_{X|Y}(3|1) + 4*p_{X|Y}(4|1)  \\
             =& P(X=1|Y=1) + 2*0 + 3*0 + 4*0  \\
             =& \frac{p_{1,1}}{P(Y=1)}  \\
             =& \frac{\frac{1}{10}}{\frac{1}{10}}  \\
             =& 1  \\
    E(X|Y=2) =& 1*p_{X|Y}(1|2) + 2*p_{X|Y}(2|2) + 3*p_{X|Y}(3|2) + 4*p_{X|Y}(4|2)  \\
             =& P(X=1|Y=2) + 2*P(X=2|Y=2) + 3*0 + 4*0  \\
             =& \frac{p_{1,2}}{P(Y=2)} + 2*\frac{p_{2,2}}{P(Y=2)}  \\
             =& \frac{\frac{1}{10}}{\frac{1}{5}} + 2*\frac{\frac{1}{10}}{\frac{1}{5}}  \\
             =& \frac{3}{2}  \\
    E(X|Y=3) =& 1*p_{X|Y}(1|3) + 2*p_{X|Y}(2|3) + 3*p_{X|Y}(3|3) + 4*p_{X|Y}(4|3)  \\
             =& P(X=1|Y=3) + 2*P(X=2|Y=3) + 3*P(X=3|Y=3) + 4*0  \\
             =& \frac{p_{1,3}}{P(Y=3)} + 2*\frac{p_{2,3}}{P(Y=3)} + 3*\frac{p_{3,3}}{P(Y=3)}  \\
             =& \frac{\frac{1}{10}}{\frac{3}{10}} + 2*\frac{\frac{1}{10}}{\frac{3}{10}} + 3*\frac{\frac{1}{10}}{\frac{3}{10}}  \\
             =& 2  \\
    E(X|Y=4) =& 1*p_{X|Y}(1|4) + 2*p_{X|Y}(2|4) + 3*p_{X|Y}(3|4) + 4*p_{X|Y}(4|4)  \\
             =& P(X=1|Y=4) + 2*P(X=2|Y=4) + 3*P(X=3|Y=4) + 4*P(X=4|Y=4)  \\
             =& \frac{p_{1,4}}{P(Y=4)} + 2*\frac{p_{2,4}}{P(Y=4)} + 3*\frac{p_{3,4}}{P(Y=4)} + 4*\frac{p_{4,4}}{P(Y=4)}  \\
             =& \frac{\frac{1}{10}}{\frac{2}{5}} + 2*\frac{\frac{1}{10}}{\frac{2}{5}} + 3*\frac{\frac{1}{10}}{\frac{2}{5}} +                     4*\frac{\frac{1}{10}}{\frac{2}{5}}  \\
             =& \frac{5}{2}  \\
  \end{aligned}
\end{equation}
  
Alternatively, we have: $E(Y|X=x) = \sum\limits_{y} y*p_{Y|X}(y|x)$. Thus:  

\begin{equation}
  \begin{aligned}
    E(Y|X=1) =& 1*p_{Y|X}(1|1) + 2*p_{Y|X}(2|1) + 3*p_{Y|X}(3|1) + 4*p_{Y|X}(4|1)  \\
             =& P(Y=1|X=1) + 2*P(Y=2|X=1) + 3*P(Y=3|X=1) + 3*P(Y=4|X=1)  \\
             =& \frac{p_{1,1}}{P(X=1)} + 2*\frac{p_{1,2}}{P(X=1)} + 3*\frac{p_{1,3}}{P(X=1)} + 4*\frac{p_{1,4}}{P(X=1)}   \\
             =& \frac{\frac{1}{10}}{\frac{2}{5}} + 2*\frac{\frac{1}{10}}{\frac{2}{5}} + 3*\frac{\frac{1}{10}}{\frac{2}{5}} + 4*\frac{\frac{1}{10}}{\frac{2}{5}}  \\
             =& \frac{5}{2}  \\
    E(Y|X=2) =& 1*p_{Y|X}(1|2) + 2*p_{Y|X}(2|2) + 3*p_{Y|X}(3|2) + 4*p_{Y|X}(4|2)  \\
             =& P(Y=1|X=2) + 2*P(Y=2|X=2) + 3*P(Y=3|X=2) + 3*P(Y=4|X=2)  \\
             =& \frac{p_{2,1}}{P(X=2)} + 2*\frac{p_{2,2}}{P(X=2)} + 3*\frac{p_{2,3}}{P(X=2)} + 4*\frac{p_{2,4}}{P(X=2)}   \\
             =& \frac{0}{\frac{3}{10}} + 2*\frac{\frac{1}{10}}{\frac{3}{10}} + 3*\frac{\frac{1}{10}}{\frac{3}{10}} +             4*\frac{\frac{1}{10}}{\frac{3}{10}}  \\
             =& 3  \\
    E(Y|X=3) =& 1*p_{Y|X}(1|3) + 2*p_{Y|X}(2|3) + 3*p_{Y|X}(3|3) + 4*p_{Y|X}(4|3)  \\
             =& P(Y=1|X=3) + 2*P(Y=2|X=3) + 3*P(Y=3|X=3) + 3*P(Y=4|X=3)  \\
             =& \frac{p_{3,1}}{P(X=3)} + 2*\frac{p_{3,2}}{P(X=3)} + 3*\frac{p_{3,3}}{P(X=3)} + 4*\frac{p_{3,4}}{P(X=3)}   \\
             =& \frac{0}{\frac{1}{5}} + 2*\frac{0}{\frac{1}{5}} + 3*\frac{\frac{1}{10}}{\frac{1}{5}} + 4*\frac{\frac{1}{10}}{\frac{1}{5}}  \\
             =& \frac{7}{2}  \\
    E(Y|X=4) =& 1*p_{Y|X}(1|4) + 2*p_{Y|X}(2|4) + 3*p_{Y|X}(3|4) + 4*p_{Y|X}(4|4)  \\
             =& P(Y=1|X=4) + 2*P(Y=2|X=4) + 3*P(Y=3|X=4) + 3*P(Y=4|X=4)  \\
             =& \frac{p_{4,1}}{P(X=4)} + 2*\frac{p_{4,2}}{P(X=4)} + 3*\frac{p_{4,3}}{P(X=4)} + 4*\frac{p_{4,4}}{P(X=4)}   \\
             =& \frac{0}{\frac{1}{5}} + 2*\frac{0}{\frac{1}{5}} + 3*\frac{0}{\frac{1}{5}} + 4*\frac{\frac{1}{10}}{\frac{1}{10}}  \\
             =& 1  \\
  \end{aligned}
\end{equation}  

# **Question 3**  

We have multiple sample spaces $\Omega$ with their respective subsets $s$ as follow:  

B,G = (row,col)          | 0               | 1                      | 2                       | 3               | B (Marginal)
---          | ---             | ---                    | ---                     | ---             | ---  
0            | $\emptyset$     | $\{G\}$                | $\{GG\}$                | $\{ GGG\}$      | NA
1            | $\{B\}$         | $\{BG, GB\}$           | $\{BGG, GBG, GGB\}$     | $\emptyset$     | NA
2            | $\{BB\}$        | $\{BBG, BGB, GBB\}$    | $\emptyset$             | $\emptyset$     | NA
3            | $\emptyset$     | $\emptyset$            | $\emptyset$             | $\emptyset$     | NA
G (Marginal) | NA              | NA                     | NA                      | NA              | NA
  
We have:  

\begin{equation}
  \begin{aligned}
    P(B=0, G=0) =& .15 \, \text{as given} = .15 \\
    P(B=0, G=1) =& .2 * \frac{|s_{0,1}|}{|\Omega_1|} = .2 * \frac{1}{2} = .1  \\
    P(B=1, G=0) =& .2 * \frac{|s_{1,0}|}{|\Omega_1|} = .2 * \frac{1}{2} = .1  \\
    P(B=0, G=2) =& .35 * \frac{|s_{0,2}|}{|\Omega_2|} = .35 * \frac{1}{4} = .0875  \\
    P(B=1, G=1) =& .35 * \frac{|s_{1,1}|}{|\Omega_2|} = .35 * \frac{2}{4} = .175   \\
    P(B=2, G=0) =& .35 * \frac{|s_{2,0}|}{|\Omega_2|} = .35 * \frac{1}{4} = .0875  \\
    P(B=0, G=3) =& .30 * \frac{|s_{0,3}|}{|\Omega_3|} = .3 * \frac{1}{8} = .0375  \\
    P(B=1, G=2) =& .30 * \frac{|s_{1,2}|}{|\Omega_3|} = .3 * \frac{3}{8} = .1125  \\
    P(B=2, G=1) =& .30 * \frac{|s_{2,1}|}{|\Omega_3|} = .3 * \frac{3}{8} = .1125  \\
    P(B=3, G=0) =& .30 * \frac{|s_{3,0}|}{|\Omega_3|} = .3 * \frac{1}{8} = .0375  \\
  \end{aligned}
\end{equation}
  
Applying the probabilities, we have the joint probability mass function $p_{(B,G)}$ as follow:  

(B,G)  = (row,col)         | 0         | 1        | 2        | 3        | B (Marginal)
---          | ---       | ---      | ---      | ---      | ---  
0            | $.15$     | $.1$     | $.0875$  | $.0375$  | $.375$
1            | $.1$      | $.175$   | $.1125$  | $0$      | $.3875$
2            | $.0875$   | $.1125$  | $0$      | $0$      | $.2$
3            | $.0375$   | $0$      | $0$      | $0$      | $.0375$
G (Marginal) | $.0375$   | $.3875$  | $.2$     | $.0375$  | $1$  

  
# **Question 4**  

Let $D_1$ nad $D_2$ denotes the resulting value of the first and second die, respectively.  
We have the sample space $\Omega_{(D_1,D_2)}$ as follow, with each tuple represents $(D_1, D_2)$:  

\begin{equation}
  \begin{aligned}
    \Omega_{D_1,D_2} =& \left\{
                        \begin{matrix}
                          (1,1), & (1,2), & (1,3), & (1,4), & (1,5), & (1,6) \\
                          (2,1), & (2,2), & (2,3), & (2,4), & (2,5), & (2,6) \\
                          (3,1), & (3,2), & (3,3), & (3,4), & (3,5), & (3,6) \\
                          (4,1), & (4,2), & (4,3), & (4,4), & (4,5), & (4,6) \\
                          (5,1), & (5,2), & (5,3), & (5,4), & (5,5), & (5,6) \\
                          (6,1), & (6,2), & (6,3), & (6,4), & (6,5), & (6,6) \\
                        \end{matrix}
                        \right\}
  \end{aligned}
\end{equation}
  
We can easily see that $|\Omega_{(D_1,D_2)}| = 36$.  

  
## (a) X is the largest value obtained, and Y is the sum of the values  

In this case, we have the random variables:  

\begin{equation}
  \begin{aligned}
    X =& max(D_1, D_2) = x \\
    Y =& D_1 + D_2 = y \\
  \end{aligned}
\end{equation}
  
From observing $\Omega_{D_1,D_2}$, we can see the set of outcomes for $X$ and $Y$ as follow:  

\begin{equation}
  \begin{aligned}
    X =& \{1,2,3, ... ,6\}  \\
    Y =& \{2,3,4, ... ,12\} \\
  \end{aligned}
\end{equation}
  
The corresponding sample space of $(X,Y)$ is:  

\begin{equation}
  \begin{aligned}
    \Omega_{X,Y} =& \left\{
                    \begin{matrix}
                      (1,2), & (2,3), & (3,4), & (4,5), & (5,6), & (6,7) \\
                      (2,3), & (2,4), & (3,5), & (4,6), & (5,7), & (6,8) \\
                      (3,4), & (3,5), & (3,6), & (4,7), & (5,8), & (6,9) \\
                      (4,5), & (4,6), & (4,7), & (4,8), & (5,9), & (6,10) \\
                      (5,6), & (5,7), & (5,8), & (5,9), & (5,10), & (6,11) \\
                      (6,7), & (6,8), & (6,9), & (6,10), & (6,11), & (6,12) \\
                    \end{matrix}
                    \right\}
  \end{aligned}
\end{equation}
  
Arrange the outcomes $(X,Y)$ into a joint probability table:  
  
($X$,$Y$) = (row,col) | 2              | 3             | 4                | 5               | 6  | 7 | 8 | 9 | 10 | 11 | 12
---      | ---            | ---           | ---              | ---             |--- |---|---|---| ---|---| ---  
1        | $\frac{1}{36}$ | 0 | 0 | 0 | 0  | 0 | 0 | 0 | 0  | 0  | 0
2        | 0  | $\frac{1}{18}$| $\frac{1}{36}$  | 0 | 0  | 0 | 0 | 0 | 0  | 0  | 0
3        | 0  | 0 | $\frac{1}{18}$ | $\frac{1}{18}$ | $\frac{1}{36}$  | 0 | 0 | 0 | 0  | 0  | 0
4        | 0  | 0 | 0 | $\frac{1}{18}$  | $\frac{1}{18}$  | $\frac{1}{18}$ | $\frac{1}{36}$ | 0 | 0  | 0  | 0
5        | 0  | 0 | 0 | 0  | $\frac{1}{18}$  | $\frac{1}{18}$ | $\frac{1}{18}$ | $\frac{1}{18}$ | $\frac{1}{36}$  | 0  | 0
6        | 0  | 0 | 0 | 0  | 0  | $\frac{1}{18}$ | $\frac{1}{18}$ | $\frac{1}{18}$ | $\frac{1}{18}$  | $\frac{1}{18}$  | $\frac{1}{36}$
  
Through inspection of the joint probability table, we can spot the pattern of the only pairs having positive probability are $(x,x) \forall y=2x$ or  $(x,y-x) \text{and }(y-x,x) \forall y<2x$. Thus the joint probability mass function is:  

\begin{equation}
  \begin{aligned}
    P(X=x, Y=y) =& \left\{
                   \begin{matrix}
                    \frac{1}{36} \quad \forall y=2x, x,y \in \mathbb N \\
                    \frac{1}{18} \quad \forall x<y<2x, x,y \in \mathbb N \\
                   \end{matrix}
                   \right.
  \end{aligned}
\end{equation}
  
## (b) X is the value on the first die, and Y is the largest value;  

In this case, we have the random variables:  

\begin{equation}
  \begin{aligned}
    X =& D_1 = x \\
    Y =& max(D_1, D_2) = y \\
  \end{aligned}
\end{equation}
  
From observing $\Omega_{D_1,D_2}$, we can see the set of outcomes for $X$ and $Y$ as follow:  

\begin{equation}
  \begin{aligned}
    X =& \{1,2,3, ... ,6\}  \\
    Y =& \{1,2,3, ... ,6\} \\
  \end{aligned}
\end{equation}
  
The corresponding sample space of $(X,Y)$ is:  

\begin{equation}
  \begin{aligned}
    \Omega_{X,Y} =& \left\{
                    \begin{matrix}
                      (1,1), & (1,2), & (1,3), & (1,4), & (1,5), & (1,6) \\
                      (2,2), & (2,2), & (2,3), & (2,4), & (2,5), & (2,6) \\
                      (3,3), & (3,3), & (3,3), & (3,4), & (3,5), & (3,6) \\
                      (4,4), & (4,4), & (4,4), & (4,4), & (4,5), & (4,6) \\
                      (5,5), & (5,5), & (5,5), & (5,5), & (5,5), & (5,6) \\
                      (6,6), & (6,6), & (6,6), & (6,6), & (6,6), & (6,6) \\
                    \end{matrix}
                    \right\}
  \end{aligned}
\end{equation}
  
Arrange the outcomes $(X,Y)$ into a joint probability table:  

($X$,$Y$)  = (row,col) | 1              | 2             | 3              | 4              | 5               | 6 
---                    | ---            | ---           | ---            | ---            |---              |---
1                      | $\frac{1}{36}$ | $\frac{1}{36}$| $\frac{1}{36}$ | $\frac{1}{36}$ | $\frac{1}{36}$  | $\frac{1}{36}$ 
2                      | 0              | $\frac{1}{18}$| $\frac{1}{36}$ | $\frac{1}{36}$ | $\frac{1}{36}$  | $\frac{1}{36}$
3                      | 0              | 0             | $\frac{1}{12}$ | $\frac{1}{36}$ | $\frac{1}{36}$  | $\frac{1}{36}$
4                      | 0              | 0             | 0              | $\frac{1}{9}$  | $\frac{1}{36}$  | $\frac{1}{36}$
5                      | 0              | 0             | 0              | 0              | $\frac{5}{36}$  | $\frac{1}{36}$
6                      | 0              | 0             | 0              | 0              | 0               | $\frac{1}{6}$ 
  
Through inspection, we have the joint probability mass function:  

\begin{equation}
  \begin{aligned}
    P(X=x, Y=y) =& \left\{
                   \begin{matrix}
                    \frac{x}{36} \quad \forall x=y, x,y \in \mathbb N \\
                    \frac{1}{36} \quad \forall x<y, x,y \in \mathbb N \\
                   \end{matrix}
                   \right.
  \end{aligned}
\end{equation}
  
## (c) X is the smallest value, and Y is the largest.  

In this case, we have the random variables:  

\begin{equation}
  \begin{aligned}
    X =& min(D_1,D_2) = x \\
    Y =& max(D_1, D_2) = y \\
  \end{aligned}
\end{equation}
  
From observing $\Omega_{D_1,D_2}$, we can see the set of outcomes for $X$ and $Y$ as follow:  

\begin{equation}
  \begin{aligned}
    X =& \{1,2,3, ... ,6\}  \\
    Y =& \{1,2,3, ... ,6\} \\
  \end{aligned}
\end{equation}
  
The corresponding sample space of $(X,Y)$ is:  

\begin{equation}
  \begin{aligned}
    \Omega_{X,Y} =& \left\{
                    \begin{matrix}
                      (1,1), & (1,2), & (1,3), & (1,4), & (1,5), & (1,6) \\
                      (1,2), & (2,2), & (2,3), & (2,4), & (2,5), & (2,6) \\
                      (1,3), & (2,3), & (3,3), & (3,4), & (3,5), & (3,6) \\
                      (1,4), & (2,4), & (3,4), & (4,4), & (4,5), & (4,6) \\
                      (1,5), & (2,5), & (3,5), & (4,5), & (5,5), & (5,6) \\
                      (1,6), & (2,6), & (3,6), & (4,6), & (5,6), & (6,6) \\
                    \end{matrix}
                    \right\}
  \end{aligned}
\end{equation}
  
Arrange the outcomes $(X,Y)$ into a joint probability table:  

($X$,$Y$)  = (row,col) | 1              | 2             | 3              | 4              | 5               | 6 
---                    | ---            | ---           | ---            | ---            |---              |---
1                      | $\frac{1}{36}$ | $\frac{1}{18}$| $\frac{1}{18}$ | $\frac{1}{18}$ | $\frac{1}{18}$  | $\frac{1}{18}$ 
2                      | 0              | $\frac{1}{36}$| $\frac{1}{18}$ | $\frac{1}{18}$ | $\frac{1}{18}$  | $\frac{1}{18}$
3                      | 0              | 0             | $\frac{1}{36}$ | $\frac{1}{18}$ | $\frac{1}{18}$  | $\frac{1}{18}$
4                      | 0              | 0             | 0              | $\frac{1}{36}$ | $\frac{1}{18}$  | $\frac{1}{18}$
5                      | 0              | 0             | 0              | 0              | $\frac{1}{36}$  | $\frac{1}{18}$
6                      | 0              | 0             | 0              | 0              | 0               | $\frac{1}{36}$ 
  
Through inspection, we have the joint probability mass function:  

\begin{equation}
  \begin{aligned}
    P(X=x, Y=y) =& \left\{
                   \begin{matrix}
                    \frac{1}{36} \quad \forall x=y, x,y \in \mathbb N \\
                    \frac{1}{18} \quad \forall x<y, x,y \in \mathbb N \\
                   \end{matrix}
                   \right.
  \end{aligned}
\end{equation}
  
# **Question 5**  

## (a) X is the largest value obtained, and Y is the sum of the values
  
Arrange the outcomes $(X,Y)$ into a joint probability table:  
  
($X$,$Y$) = (row,col) | 2              | 3             | 4                | 5               | 6  | 7 | 8 | 9 | 10 | 11 | 12 | X
---      | ---            | ---           | ---              | ---             |--- |---|---|---| ---|---| ---  |---
1        | $\frac{1}{36}$ | 0 | 0 | 0 | 0  | 0 | 0 | 0 | 0  | 0  | 0 | $\frac{1}{36}$
2        | 0  | $\frac{1}{18}$| $\frac{1}{36}$  | 0 | 0  | 0 | 0 | 0 | 0  | 0  | 0 |$\frac{1}{12}$
3        | 0  | 0 | $\frac{1}{18}$ | $\frac{1}{18}$ | $\frac{1}{36}$  | 0 | 0 | 0 | 0  | 0  | 0 | $\frac{5}{36}$ 
4        | 0  | 0 | 0 | $\frac{1}{18}$  | $\frac{1}{18}$  | $\frac{1}{18}$ | $\frac{1}{36}$ | 0 | 0  | 0  | 0 | $\frac{7}{36}$
5        | 0  | 0 | 0 | 0  | $\frac{1}{18}$  | $\frac{1}{18}$ | $\frac{1}{18}$ | $\frac{1}{18}$ | $\frac{1}{36}$  | 0  | 0 |$\frac{1}{4}$
6        | 0  | 0 | 0 | 0  | 0  | $\frac{1}{18}$ | $\frac{1}{18}$ | $\frac{1}{18}$ | $\frac{1}{18}$  | $\frac{1}{18}$  | $\frac{1}{36}$ |$\frac{11}{36}$
Y        | $\frac{1}{36}$  | $\frac{1}{18}$ | $\frac{1}{12}$ | $\frac{1}{9}$  | $\frac{5}{36}$  | $\frac{1}{6}$ | $\frac{5}{36}$ | $\frac{1}{9}$ | $\frac{1}{12}$  | $\frac{1}{18}$  | $\frac{1}{36}$  | 1
  
We have: $E(Y|X=x) = \sum\limits_{y} x*p_{Y|X}(y|x)$. Thus:  

\begin{equation}
  \begin{aligned}
    E(Y|X=1) =& 2*p_{Y|X}(2|1) + 3*p_{Y|X}(3|1) + 4*p_{Y|X}(4|1) + 5*p_{Y|X}(5|1) + 6*p_{Y|X}(6|1) + 7*p_{Y|X}(7|1) + \\
              & 8*p_{Y|X}(8|1) + 9*p_{Y|X}(9|1) + 10*p_{Y|X}(10|1) + 11*p_{Y|X}(11|1) + 12*p_{Y|X}(12|1)  \\
             =& 2*P(Y=2|X=1) + 3*P(Y=3|X=1) + 4*P(Y=4|X=1) + 5*P(Y=5|X=1) + 6*p_{Y|X}(6|1) + 7*p_{Y|X}(7|1) + \\
              & 8*p_{Y|X}(8|1) + 9*p_{Y|X}(9|1) + 10*p_{Y|X}(10|1) + 11*p_{Y|X}(11|1) + 12*p_{Y|X}(12|1)  \\
             =& 2*\frac{p_{1,2}}{P(X=1)} + 3*\frac{p_{1,3}}{P(X=1)} + 4*\frac{p_{1,4}}{P(X=1)} + 5*\frac{p_{1,5}}{P(X=1)} + \\
              & 6*\frac{p_{1,6}}{P(X=1)} + 7*\frac{p_{1,7}}{P(X=1)} + 8*\frac{p_{1,8}}{P(X=1)} + 9*\frac{p_{1,9}}{P(X=1)} + \\
              & 10*\frac{p_{1,10}}{P(X=1)} + 11*\frac{p_{1,11}}{P(X=1)} + 12*\frac{p_{1,12}}{P(X=1)}   \\
             =& 2*\frac{\frac{1}{36}}{\frac{1}{36}} + 3*\frac{0}{\frac{1}{36}} + 4*\frac{0}{\frac{1}{36}} + 5*\frac{0}{\frac{1}{36}} +  \\
              & 6*\frac{0}{\frac{1}{36}} + 7*\frac{0}{\frac{1}{36}} + 8*\frac{0}{\frac{1}{36}} + 9*\frac{0}{\frac{1}{36}} + \\
              & 10*\frac{0}{\frac{1}{36}} + 11*\frac{0}{\frac{1}{36}} + 12*\frac{0}{\frac{1}{36}}   \\
             =& 2\\
    E(Y|X=2) =& 2*p_{Y|X}(2|2) + 3*p_{Y|X}(3|2) + 4*p_{Y|X}(4|2) + 5*p_{Y|X}(5|2) + 6*p_{Y|X}(6|2) + 7*p_{Y|X}(7|2) + \\
              & 8*p_{Y|X}(8|2) + 9*p_{Y|X}(9|2) + 10*p_{Y|X}(10|2) + 11*p_{Y|X}(11|2) + 12*p_{Y|X}(12|2)  \\
             =& 2*P(Y=2|X=2) + 3*P(Y=3|X=2) + 4*P(Y=4|X=2) + 5*P(Y=5|X=2) + 6*p_{Y|X}(6|2) + 7*p_{Y|X}(7|2) + \\
              & 8*p_{Y|X}(8|2) + 9*p_{Y|X}(9|2) + 10*p_{Y|X}(10|2) + 11*p_{Y|X}(11|2) + 12*p_{Y|X}(12|2)  \\
             =& 2*\frac{p_{2,2}}{P(X=2)} + 3*\frac{p_{2,3}}{P(X=2)} + 4*\frac{p_{2,4}}{P(X=2)} + 5*\frac{p_{2,5}}{P(X=2)} + \\
              & 6*\frac{p_{2,6}}{P(X=2)} + 7*\frac{p_{2,7}}{P(X=2)} + 8*\frac{p_{2,8}}{P(X=2)} + 9*\frac{p_{2,9}}{P(X=2)} + \\
              & 10*\frac{p_{2,10}}{P(X=2)} + 11*\frac{p_{2,11}}{P(X=2)} + 12*\frac{p_{2,12}}{P(X=2)}   \\
             =& 2*\frac{0}{\frac{1}{12}} + 3*\frac{\frac{1}{18}}{\frac{1}{12}} + 4*\frac{\frac{1}{36}}{\frac{1}{12}} + 5*\frac{0}{\frac{1}{12}} +  \\
              & 6*\frac{0}{\frac{1}{12}} + 7*\frac{0}{\frac{1}{12}} + 8*\frac{0}{\frac{1}{12}} + 9*\frac{0}{\frac{1}{12}} + \\
              & 10*\frac{0}{\frac{1}{12}} + 11*\frac{0}{\frac{1}{12}} + 12*\frac{0}{\frac{1}{12}}   \\
             =& \frac{10}{3}\\
    E(Y|X=3) =& 2*p_{Y|X}(2|3) + 3*p_{Y|X}(3|3) + 4*p_{Y|X}(4|3) + 5*p_{Y|X}(5|3) + 6*p_{Y|X}(6|3) + 7*p_{Y|X}(7|3) + \\
              & 8*p_{Y|X}(8|3) + 9*p_{Y|X}(9|3) + 10*p_{Y|X}(10|3) + 11*p_{Y|X}(11|3) + 12*p_{Y|X}(12|3)  \\
             =& 2*P(Y=2|X=3) + 3*P(Y=3|X=3) + 4*P(Y=4|X=3) + 5*P(Y=5|X=3) + 6*p_{Y|X}(6|3) + 7*p_{Y|X}(7|3) + \\
              & 8*p_{Y|X}(8|3) + 9*p_{Y|X}(9|3) + 10*p_{Y|X}(10|3) + 11*p_{Y|X}(11|3) + 12*p_{Y|X}(12|3)  \\
             =& 2*\frac{p_{3,2}}{P(X=3)} + 3*\frac{p_{3,3}}{P(X=3)} + 4*\frac{p_{3,4}}{P(X=3)} + 5*\frac{p_{3,5}}{P(X=3)} + \\
              & 6*\frac{p_{3,6}}{P(X=3)} + 7*\frac{p_{3,7}}{P(X=3)} + 8*\frac{p_{3,8}}{P(X=3)} + 9*\frac{p_{3,9}}{P(X=3)} + \\
              & 10*\frac{p_{3,10}}{P(X=3)} + 11*\frac{p_{3,11}}{P(X=3)} + 12*\frac{p_{3,12}}{P(X=3)}   \\
             =& 2*\frac{0}{\frac{5}{36}} + 3*\frac{0}{\frac{5}{36}} + 4*\frac{\frac{1}{18}}{\frac{5}{36}} + 5*\frac{\frac{1}{18}}{\frac{5}{36}} +  \\
              & 6*\frac{\frac{1}{36}}{\frac{5}{36}} + 7*\frac{0}{\frac{5}{36}} + 8*\frac{0}{\frac{5}{36}} + 9*\frac{0}{\frac{5}{36}} + \\
              & 10*\frac{0}{\frac{5}{36}} + 11*\frac{0}{\frac{5}{36}} + 12*\frac{0}{\frac{5}{36}}   \\
             =& \frac{24}{5}\\
    E(Y|X=4) =& 2*p_{Y|X}(2|4) + 3*p_{Y|X}(3|4) + 4*p_{Y|X}(4|4) + 5*p_{Y|X}(5|4) + 6*p_{Y|X}(6|4) + 7*p_{Y|X}(7|4) + \\
              & 8*p_{Y|X}(8|4) + 9*p_{Y|X}(9|4) + 10*p_{Y|X}(10|4) + 11*p_{Y|X}(11|4) + 12*p_{Y|X}(12|4)  \\
             =& 2*P(Y=2|X=4) + 3*P(Y=3|X=4) + 4*P(Y=4|X=4) + 5*P(Y=5|X=4) + 6*p_{Y|X}(6|4) + 7*p_{Y|X}(7|4) + \\
              & 8*p_{Y|X}(8|4) + 9*p_{Y|X}(9|4) + 10*p_{Y|X}(10|4) + 11*p_{Y|X}(11|4) + 12*p_{Y|X}(12|4)  \\
             =& 2*\frac{p_{4,2}}{P(X=4)} + 3*\frac{p_{4,3}}{P(X=4)} + 4*\frac{p_{4,4}}{P(X=4)} + 5*\frac{p_{4,5}}{P(X=4)} + \\
              & 6*\frac{p_{4,6}}{P(X=4)} + 7*\frac{p_{4,7}}{P(X=4)} + 8*\frac{p_{4,8}}{P(X=4)} + 9*\frac{p_{4,9}}{P(X=4)} + \\
              & 10*\frac{p_{4,10}}{P(X=4)} + 11*\frac{p_{4,11}}{P(X=4)} + 12*\frac{p_{4,12}}{P(X=4)}   \\
             =& 2*\frac{0}{\frac{7}{36}} + 3*\frac{0}{\frac{7}{36}} + 4*\frac{0}{\frac{7}{36}} + 5*\frac{\frac{1}{18}}{\frac{7}{36}} +  \\
              & 6*\frac{\frac{1}{18}}{\frac{7}{36}} + 7*\frac{\frac{1}{18}}{\frac{7}{36}} + 8*\frac{\frac{1}{36}}{\frac{7}{36}} + 9*\frac{0}{\frac{7}{36}} + \\
              & 10*\frac{0}{\frac{7}{36}} + 11*\frac{0}{\frac{7}{36}} + 12*\frac{0}{\frac{7}{36}}   \\
             =& \frac{44}{7}\\
    E(Y|X=5) =& 2*p_{Y|X}(2|5) + 3*p_{Y|X}(3|5) + 4*p_{Y|X}(4|5) + 5*p_{Y|X}(5|5) + 6*p_{Y|X}(6|5) + 7*p_{Y|X}(7|5) + \\
              & 8*p_{Y|X}(8|5) + 9*p_{Y|X}(9|5) + 10*p_{Y|X}(10|5) + 11*p_{Y|X}(11|5) + 12*p_{Y|X}(12|5)  \\
             =& 2*P(Y=2|X=5) + 3*P(Y=3|X=5) + 4*P(Y=4|X=5) + 5*P(Y=5|X=5) + 6*p_{Y|X}(6|5) + 7*p_{Y|X}(7|5) + \\
              & 8*p_{Y|X}(8|5) + 9*p_{Y|X}(9|5) + 10*p_{Y|X}(10|5) + 11*p_{Y|X}(11|5) + 12*p_{Y|X}(12|5)  \\
             =& 2*\frac{p_{5,2}}{P(X=5)} + 3*\frac{p_{5,3}}{P(X=5)} + 4*\frac{p_{5,4}}{P(X=5)} + 5*\frac{p_{5,5}}{P(X=5)} + \\
              & 6*\frac{p_{5,6}}{P(X=5)} + 7*\frac{p_{5,7}}{P(X=5)} + 8*\frac{p_{5,8}}{P(X=5)} + 9*\frac{p_{5,9}}{P(X=5)} + \\
              & 10*\frac{p_{5,10}}{P(X=5)} + 11*\frac{p_{5,11}}{P(X=5)} + 12*\frac{p_{5,12}}{P(X=5)}   \\
             =& 2*\frac{0}{\frac{1}{4}} + 3*\frac{0}{\frac{1}{4}} + 4*\frac{0}{\frac{1}{4}} + 5*\frac{0}{\frac{1}{4}} +  \\
              & 6*\frac{\frac{1}{18}}{\frac{1}{4}} + 7*\frac{\frac{1}{18}}{\frac{1}{4}} + 8*\frac{\frac{1}{18}}{\frac{1}{4}} + 9*\frac{\frac{1}{18}}{\frac{1}{4}} + \\
              & 10*\frac{\frac{1}{36}}{\frac{1}{4}} + 11*\frac{0}{\frac{1}{4}} + 12*\frac{0}{\frac{1}{4}}   \\
             =& \frac{70}{9}\\
    E(Y|X=6) =& 2*p_{Y|X}(2|6) + 3*p_{Y|X}(3|6) + 4*p_{Y|X}(4|6) + 5*p_{Y|X}(5|6) + 6*p_{Y|X}(6|6) + 7*p_{Y|X}(7|6) + \\
              & 8*p_{Y|X}(8|6) + 9*p_{Y|X}(9|6) + 10*p_{Y|X}(10|6) + 11*p_{Y|X}(11|6) + 12*p_{Y|X}(12|6)  \\
             =& 2*P(Y=2|X=6) + 3*P(Y=3|X=6) + 4*P(Y=4|X=6) + 5*P(Y=5|X=6) + 6*p_{Y|X}(6|6) + 7*p_{Y|X}(7|6) + \\
              & 8*p_{Y|X}(8|6) + 9*p_{Y|X}(9|6) + 10*p_{Y|X}(10|6) + 11*p_{Y|X}(11|6) + 12*p_{Y|X}(12|6)  \\
             =& 2*\frac{p_{6,2}}{P(X=6)} + 3*\frac{p_{6,3}}{P(X=6)} + 4*\frac{p_{6,4}}{P(X=6)} + 5*\frac{p_{6,5}}{P(X=6)} + \\
              & 6*\frac{p_{6,6}}{P(X=6)} + 7*\frac{p_{6,7}}{P(X=6)} + 8*\frac{p_{6,8}}{P(X=6)} + 9*\frac{p_{6,9}}{P(X=6)} + \\
              & 10*\frac{p_{6,10}}{P(X=6)} + 11*\frac{p_{6,11}}{P(X=6)} + 12*\frac{p_{6,12}}{P(X=6)}   \\
             =& 2*\frac{0}{\frac{11}{36}} + 3*\frac{0}{\frac{11}{36}} + 4*\frac{0}{\frac{11}{36}} + 5*\frac{0}{\frac{11}{36}} +  \\
              & 6*\frac{0}{\frac{11}{36}} + 7*\frac{\frac{1}{18}}{\frac{11}{36}} + 8*\frac{\frac{1}{18}}{\frac{11}{36}} + 9*\frac{\frac{1}{18}}{\frac{11}{36}} + \\
              & 10*\frac{\frac{1}{18}}{\frac{11}{36}} + 11*\frac{\frac{1}{18}}{\frac{11}{36}} + 12*\frac{\frac{1}{36}}{\frac{11}{36}}   \\
             =& \frac{102}{11}\\
  \end{aligned}
\end{equation}  

## (b) X is the value on the first die, and Y is the largest value;  

Arrange the outcomes $(X,Y)$ into a joint probability table:  

($X$,$Y$)  = (row,col) | 1              | 2             | 3              | 4              | 5               | 6              | X
---                    | ---            | ---           | ---            | ---            |---              |---             |---
1                      | $\frac{1}{36}$ | $\frac{1}{36}$| $\frac{1}{36}$ | $\frac{1}{36}$ | $\frac{1}{36}$  | $\frac{1}{36}$ | $\frac{1}{6}$
2                      | 0              | $\frac{1}{18}$| $\frac{1}{36}$ | $\frac{1}{36}$ | $\frac{1}{36}$  | $\frac{1}{36}$ | $\frac{1}{6}$
3                      | 0              | 0             | $\frac{1}{12}$ | $\frac{1}{36}$ | $\frac{1}{36}$  | $\frac{1}{36}$ | $\frac{1}{6}$
4                      | 0              | 0             | 0              | $\frac{1}{9}$  | $\frac{1}{36}$  | $\frac{1}{36}$ | $\frac{1}{6}$
5                      | 0              | 0             | 0              | 0              | $\frac{5}{36}$  | $\frac{1}{36}$ | $\frac{1}{6}$
6                      | 0              | 0             | 0              | 0              | 0               | $\frac{1}{6}$  | $\frac{1}{6}$
Y                      | $\frac{1}{36}$ | $\frac{1}{12}$| $\frac{5}{36}$ | $\frac{7}{36}$ | $\frac{1}{4}$   | $\frac{1}{4}$  | 1
  
We have: $E(Y|X=x) = \sum\limits_{y} x*p_{Y|X}(y|x)$. Thus:  

\begin{equation}
  \begin{aligned}
    E(Y|X=1) =& 1*p_{Y|X}(1|1) + 2*p_{Y|X}(2|1) + 3*p_{Y|X}(3|1) + \\
              & 4*p_{Y|X}(4|1) + 5*p_{Y|X}(5|1) + 6*p_{Y|X}(6|1) \\
             =& 1*P(Y=1|X=1) + 2*P(Y=2|X=1) + 3*P(Y=3|X=1) + \\
              & 4*P(Y=4|X=1) + 5*P(Y=5|X=1) + 6*P(Y=6|X=1) \\
             =& 1*\frac{p_{1,1}}{P(X=1)} + 2*\frac{p_{1,2}}{P(X=1)} + 3*\frac{p_{1,3}}{P(X=1)} + \\
              & 4*\frac{p_{1,4}}{P(X=1)} + 5*\frac{p_{1,5}}{P(X=1)} + 6*\frac{p_{1,6}}{P(X=1)} \\
             =& 1*\frac{\frac{1}{36}}{\frac{1}{6}} + 2*\frac{\frac{1}{36}}{\frac{1}{6}} + 3*\frac{\frac{1}{36}}{\frac{1}{6}} + \\ 
              & 4*\frac{\frac{1}{36}}{\frac{1}{6}} + 5*\frac{\frac{1}{36}}{\frac{1}{6}} + 6*\frac{\frac{1}{36}}{\frac{1}{6}} \\ 
             =& \frac{21}{16} \\
    E(Y|X=2) =& 1*p_{Y|X}(1|2) + 2*p_{Y|X}(2|2) + 3*p_{Y|X}(3|2) + \\
              & 4*p_{Y|X}(4|2) + 5*p_{Y|X}(5|2) + 6*p_{Y|X}(6|2) \\
             =& 1*P(Y=1|X=2) + 2*P(Y=2|X=2) + 3*P(Y=3|X=2) + \\
              & 4*P(Y=4|X=2) + 5*P(Y=5|X=2) + 6*P(Y=6|X=2) + \\
             =& 1*\frac{p_{2,1}}{P(X=2)} + 2*\frac{p_{2,2}}{P(X=2)} + 3*\frac{p_{2,3}}{P(X=2)} + \\
              & 4*\frac{p_{2,4}}{P(X=2)} + 5*\frac{p_{2,5}}{P(X=2)} + 6*\frac{p_{2,6}}{P(X=2)} \\
             =& 1*\frac{0}{\frac{1}{6}} + 2*\frac{\frac{1}{18}}{\frac{1}{6}} + 3*\frac{\frac{1}{36}}{\frac{1}{6}} + \\ 
              & 4*\frac{\frac{1}{36}}{\frac{1}{6}} + 5*\frac{\frac{1}{36}}{\frac{1}{6}} + 6*\frac{\frac{1}{36}}{\frac{1}{6}} \\ 
             =& \frac{11}{3} \\
    E(Y|X=3) =& 1*p_{Y|X}(1|3) + 2*p_{Y|X}(2|3) + 3*p_{Y|X}(3|3) + \\
              & 4*p_{Y|X}(4|3) + 5*p_{Y|X}(5|3) + 6*p_{Y|X}(6|3) \\
             =& 1*P(Y=1|X=3) + 2*P(Y=2|X=3) + 3*P(Y=3|X=3) + \\
              & 4*P(Y=4|X=3) + 5*P(Y=5|X=3) + 6*P(Y=6|X=3) + \\
             =& 1*\frac{p_{3,1}}{P(X=3)} + 2*\frac{p_{3,2}}{P(X=3)} + 3*\frac{p_{3,3}}{P(X=3)} + \\
              & 4*\frac{p_{3,4}}{P(X=3)} + 5*\frac{p_{3,5}}{P(X=3)} + 6*\frac{p_{3,6}}{P(X=3)} \\
             =& 1*\frac{0}{\frac{1}{6}} + 2*\frac{0}{\frac{1}{6}} + 3*\frac{\frac{1}{12}}{\frac{1}{6}} + \\ 
              & 4*\frac{\frac{1}{36}}{\frac{1}{6}} + 5*\frac{\frac{1}{36}}{\frac{1}{6}} + 6*\frac{\frac{1}{36}}{\frac{1}{6}} \\ 
             =& 4 \\
    E(Y|X=4) =& 1*p_{Y|X}(1|4) + 2*p_{Y|X}(2|4) + 3*p_{Y|X}(3|4) + \\
              & 4*p_{Y|X}(4|4) + 5*p_{Y|X}(5|4) + 6*p_{Y|X}(6|4) \\
             =& 1*P(Y=1|X=4) + 2*P(Y=2|X=4) + 3*P(Y=3|X=4) + \\
              & 4*P(Y=4|X=4) + 5*P(Y=5|X=4) + 6*P(Y=6|X=4) + \\
             =& 1*\frac{p_{4,1}}{P(X=4)} + 2*\frac{p_{4,2}}{P(X=4)} + 3*\frac{p_{4,3}}{P(X=4)} + \\
              & 4*\frac{p_{4,4}}{P(X=4)} + 5*\frac{p_{4,5}}{P(X=4)} + 6*\frac{p_{4,6}}{P(X=4)} \\
             =& 1*\frac{0}{\frac{1}{6}} + 2*\frac{0}{\frac{1}{6}} + 3*\frac{0}{\frac{1}{6}} + \\ 
              & 4*\frac{\frac{1}{9}}{\frac{1}{6}} + 5*\frac{\frac{1}{36}}{\frac{1}{6}} + 6*\frac{\frac{1}{36}}{\frac{1}{6}} \\ 
             =& \frac{9}{2} \\
    E(Y|X=5) =& 1*p_{Y|X}(1|5) + 2*p_{Y|X}(2|5) + 3*p_{Y|X}(3|5) + \\
              & 4*p_{Y|X}(4|5) + 5*p_{Y|X}(5|5) + 6*p_{Y|X}(6|5) \\
             =& 1*P(Y=1|X=5) + 2*P(Y=2|X=5) + 3*P(Y=3|X=5) + \\
              & 4*P(Y=4|X=5) + 5*P(Y=5|X=5) + 6*P(Y=6|X=5) + \\
             =& 1*\frac{p_{5,1}}{P(X=5)} + 2*\frac{p_{5,2}}{P(X=5)} + 3*\frac{p_{5,3}}{P(X=5)} + \\
              & 4*\frac{p_{5,4}}{P(X=5)} + 5*\frac{p_{5,5}}{P(X=5)} + 6*\frac{p_{5,6}}{P(X=5)} \\
             =& 1*\frac{0}{\frac{1}{6}} + 2*\frac{0}{\frac{1}{6}} + 3*\frac{0}{\frac{1}{6}} + \\ 
              & 4*\frac{0}{\frac{1}{6}} + 5*\frac{\frac{5}{36}}{\frac{1}{6}} + 6*\frac{\frac{1}{36}}{\frac{1}{6}} \\ 
             =& \frac{31}{6} \\
    E(Y|X=6) =& 1*p_{Y|X}(1|6) + 2*p_{Y|X}(2|6) + 3*p_{Y|X}(3|6) + \\
              & 4*p_{Y|X}(4|6) + 5*p_{Y|X}(5|6) + 6*p_{Y|X}(6|6) \\
             =& 1*P(Y=1|X=6) + 2*P(Y=2|X=6) + 3*P(Y=3|X=6) + \\
              & 4*P(Y=4|X=6) + 5*P(Y=5|X=6) + 6*P(Y=6|X=6) + \\
             =& 1*\frac{p_{6,1}}{P(X=6)} + 2*\frac{p_{6,2}}{P(X=6)} + 3*\frac{p_{6,3}}{P(X=6)} + \\
              & 4*\frac{p_{6,4}}{P(X=6)} + 5*\frac{p_{6,5}}{P(X=6)} + 6*\frac{p_{6,6}}{P(X=6)} \\
             =& 1*\frac{0}{\frac{1}{6}} + 2*\frac{0}{\frac{1}{6}} + 3*\frac{0}{\frac{1}{6}} + \\ 
              & 4*\frac{0}{\frac{1}{6}} + 5*\frac{0}{\frac{1}{6}} + 6*\frac{\frac{1}{6}}{\frac{1}{6}} \\ 
             =& 6 \\
  \end{aligned}
\end{equation}  

## (c) X is the smallest value, and Y is the largest.  


Arrange the outcomes $(X,Y)$ into a joint probability table:    

($X$,$Y$)  = (row,col) | 1              | 2             | 3              | 4              | 5               | 6              | X
---                    | ---            | ---           | ---            | ---            |---              |---             |---
1                      | $\frac{1}{36}$ | $\frac{1}{18}$| $\frac{1}{18}$ | $\frac{1}{18}$ | $\frac{1}{18}$  | $\frac{1}{18}$ | $\frac{11}{36}$
2                      | 0              | $\frac{1}{36}$| $\frac{1}{18}$ | $\frac{1}{18}$ | $\frac{1}{18}$  | $\frac{1}{18}$ | $\frac{1}{4}$
3                      | 0              | 0             | $\frac{1}{36}$ | $\frac{1}{18}$ | $\frac{1}{18}$  | $\frac{1}{18}$ | $\frac{7}{36}$
4                      | 0              | 0             | 0              | $\frac{1}{36}$ | $\frac{1}{18}$  | $\frac{1}{18}$ | $\frac{5}{36}$
5                      | 0              | 0             | 0              | 0              | $\frac{1}{36}$  | $\frac{1}{18}$ | $\frac{1}{12}$
6                      | 0              | 0             | 0              | 0              | 0               | $\frac{1}{36}$ | $\frac{1}{36}$
Y                      | $\frac{1}{36}$ | $\frac{1}{12}$| $\frac{5}{36}$ | $\frac{7}{36}$ | $\frac{1}{4}$   | $\frac{11}{36}$| 1
  

We have: $E(Y|X=x) = \sum\limits_{y} x*p_{Y|X}(y|x)$. Thus:  

\begin{equation}
  \begin{aligned}
    E(Y|X=1) =& 1*p_{Y|X}(1|1) + 2*p_{Y|X}(2|1) + 3*p_{Y|X}(3|1) + \\
              & 4*p_{Y|X}(4|1) + 5*p_{Y|X}(5|1) + 6*p_{Y|X}(6|1) \\
             =& 1*P(Y=1|X=1) + 2*P(Y=2|X=1) + 3*P(Y=3|X=1) + \\
              & 4*P(Y=4|X=1) + 5*P(Y=5|X=1) + 6*P(Y=6|X=1) \\
             =& 1*\frac{p_{1,1}}{P(X=1)} + 2*\frac{p_{1,2}}{P(X=1)} + 3*\frac{p_{1,3}}{P(X=1)} + \\
              & 4*\frac{p_{1,4}}{P(X=1)} + 5*\frac{p_{1,5}}{P(X=1)} + 6*\frac{p_{1,6}}{P(X=1)} \\
             =& 1*\frac{\frac{1}{36}}{\frac{11}{36}} + 2*\frac{\frac{1}{18}}{\frac{11}{36}} + 3*\frac{\frac{1}{18}}{\frac{11}{36}} + \\ 
              & 4*\frac{\frac{1}{18}}{\frac{11}{36}} + 5*\frac{\frac{1}{18}}{\frac{11}{36}} + 6*\frac{\frac{1}{18}}{\frac{11}{36}} \\ 
             =& \frac{41}{11} \\
    E(Y|X=2) =& 1*p_{Y|X}(1|2) + 2*p_{Y|X}(2|2) + 3*p_{Y|X}(3|2) + \\
              & 4*p_{Y|X}(4|2) + 5*p_{Y|X}(5|2) + 6*p_{Y|X}(6|2) \\
             =& 1*P(Y=1|X=2) + 2*P(Y=2|X=2) + 3*P(Y=3|X=2) + \\
              & 4*P(Y=4|X=2) + 5*P(Y=5|X=2) + 6*P(Y=6|X=2) + \\
             =& 1*\frac{p_{2,1}}{P(X=2)} + 2*\frac{p_{2,2}}{P(X=2)} + 3*\frac{p_{2,3}}{P(X=2)} + \\
              & 4*\frac{p_{2,4}}{P(X=2)} + 5*\frac{p_{2,5}}{P(X=2)} + 6*\frac{p_{2,6}}{P(X=2)} \\
             =& 1*\frac{0}{\frac{1}{4}} + 2*\frac{\frac{1}{36}}{\frac{1}{4}} + 3*\frac{\frac{1}{18}}{\frac{1}{4}} + \\ 
              & 4*\frac{\frac{1}{18}}{\frac{1}{4}} + 5*\frac{\frac{1}{18}}{\frac{1}{4}} + 6*\frac{\frac{1}{18}}{\frac{1}{4}} \\ 
             =& 4 \\
    E(Y|X=3) =& 1*p_{Y|X}(1|3) + 2*p_{Y|X}(2|3) + 3*p_{Y|X}(3|3) + \\
              & 4*p_{Y|X}(4|3) + 5*p_{Y|X}(5|3) + 6*p_{Y|X}(6|3) \\
             =& 1*P(Y=1|X=3) + 2*P(Y=2|X=3) + 3*P(Y=3|X=3) + \\
              & 4*P(Y=4|X=3) + 5*P(Y=5|X=3) + 6*P(Y=6|X=3) + \\
             =& 1*\frac{p_{3,1}}{P(X=3)} + 2*\frac{p_{3,2}}{P(X=3)} + 3*\frac{p_{3,3}}{P(X=3)} + \\
              & 4*\frac{p_{3,4}}{P(X=3)} + 5*\frac{p_{3,5}}{P(X=3)} + 6*\frac{p_{3,6}}{P(X=3)} \\
             =& 1*\frac{0}{\frac{7}{36}} + 2*\frac{0}{\frac{7}{36}} + 3*\frac{\frac{1}{36}}{\frac{7}{36}} + \\ 
              & 4*\frac{\frac{1}{18}}{\frac{7}{36}} + 5*\frac{\frac{1}{18}}{\frac{7}{36}} + 6*\frac{\frac{1}{18}}{\frac{7}{36}} \\ 
             =& \frac{33}{7} \\
    E(Y|X=4) =& 1*p_{Y|X}(1|4) + 2*p_{Y|X}(2|4) + 3*p_{Y|X}(3|4) + \\
              & 4*p_{Y|X}(4|4) + 5*p_{Y|X}(5|4) + 6*p_{Y|X}(6|4) \\
             =& 1*P(Y=1|X=4) + 2*P(Y=2|X=4) + 3*P(Y=3|X=4) + \\
              & 4*P(Y=4|X=4) + 5*P(Y=5|X=4) + 6*P(Y=6|X=4) + \\
             =& 1*\frac{p_{4,1}}{P(X=4)} + 2*\frac{p_{4,2}}{P(X=4)} + 3*\frac{p_{4,3}}{P(X=4)} + \\
              & 4*\frac{p_{4,4}}{P(X=4)} + 5*\frac{p_{4,5}}{P(X=4)} + 6*\frac{p_{4,6}}{P(X=4)} \\
             =& 1*\frac{0}{\frac{5}{36}} + 2*\frac{0}{\frac{5}{36}} + 3*\frac{0}{\frac{5}{36}} + \\ 
              & 4*\frac{\frac{1}{36}}{\frac{5}{36}} + 5*\frac{\frac{1}{18}}{\frac{5}{36}} + 6*\frac{\frac{1}{18}}{\frac{5}{36}} \\ 
             =& \frac{26}{5} \\
    E(Y|X=5) =& 1*p_{Y|X}(1|5) + 2*p_{Y|X}(2|5) + 3*p_{Y|X}(3|5) + \\
              & 4*p_{Y|X}(4|5) + 5*p_{Y|X}(5|5) + 6*p_{Y|X}(6|5) \\
             =& 1*P(Y=1|X=5) + 2*P(Y=2|X=5) + 3*P(Y=3|X=5) + \\
              & 4*P(Y=4|X=5) + 5*P(Y=5|X=5) + 6*P(Y=6|X=5) + \\
             =& 1*\frac{p_{5,1}}{P(X=5)} + 2*\frac{p_{5,2}}{P(X=5)} + 3*\frac{p_{5,3}}{P(X=5)} + \\
              & 4*\frac{p_{5,4}}{P(X=5)} + 5*\frac{p_{5,5}}{P(X=5)} + 6*\frac{p_{5,6}}{P(X=5)} \\
             =& 1*\frac{0}{\frac{1}{12}} + 2*\frac{0}{\frac{1}{12}} + 3*\frac{0}{\frac{1}{12}} + \\ 
              & 4*\frac{0}{\frac{1}{12}} + 5*\frac{\frac{1}{36}}{\frac{1}{12}} + 6*\frac{\frac{1}{18}}{\frac{1}{12}} \\ 
             =& \frac{17}{3} \\
    E(Y|X=6) =& 1*p_{Y|X}(1|6) + 2*p_{Y|X}(2|6) + 3*p_{Y|X}(3|6) + \\
              & 4*p_{Y|X}(4|6) + 5*p_{Y|X}(5|6) + 6*p_{Y|X}(6|6) \\
             =& 1*P(Y=1|X=6) + 2*P(Y=2|X=6) + 3*P(Y=3|X=6) + \\
              & 4*P(Y=4|X=6) + 5*P(Y=5|X=6) + 6*P(Y=6|X=6) + \\
             =& 1*\frac{p_{6,1}}{P(X=6)} + 2*\frac{p_{6,2}}{P(X=6)} + 3*\frac{p_{6,3}}{P(X=6)} + \\
              & 4*\frac{p_{6,4}}{P(X=6)} + 5*\frac{p_{6,5}}{P(X=6)} + 6*\frac{p_{6,6}}{P(X=6)} \\
             =& 1*\frac{0}{\frac{1}{36}} + 2*\frac{0}{\frac{1}{36}} + 3*\frac{0}{\frac{1}{36}} + \\ 
              & 4*\frac{0}{\frac{1}{36}} + 5*\frac{0}{\frac{1}{36}} + 6*\frac{\frac{1}{36}}{\frac{1}{36}} \\ 
             =& 6 \\
  \end{aligned}
\end{equation}  

# **Question 6-10**  

Did not have time to do them. Homework too long. RIP.
